const axios = require('axios');
const engine = require('./autopilotMaterialEngine');
const { getAccount, getSystemApiSettings } = require('./db');
const originalBuild = engine.buildThreadsFirstAutopilot.bind(engine);
function getOpenAIKey(accountId){const a=getAccount(accountId);const s=getSystemApiSettings();return s.openai_api_key||process.env.OPENAI_API_KEY||a?.openai_api_key||null;}
function clean(t){return String(t||'').replace(/\r/g,'').replace(/,/g,'').replace(/(^|[^0-9])\.(?![0-9])/g,'$1').split('\n').map(x=>x.trim()).join('\n').replace(/\n{3,}/g,'\n\n').trim();}
function mergeAwkwardLineBreaks(text){const raw=clean(text);if(!raw)return raw;const src=raw.split('\n'),out=[];const dangling=/(은|는|이|가|을|를|도|만|에|의|와|과|로|으로|부터|까지|해서|하고|는데|니까|면|지만|다가|거나|처럼|보다|정도|때문에|보니까|하면서|쓰면|먹으면)$/;const frag=/^(같아|같네|같아서|같으니까|좋고|좋아|있어|없어|했어|돼|되고|해서|하고|보여|보이고|느껴|느낌이|때문에)/;const bridge=/^(매일|매번|요즘|그냥|진짜|이거|그래서|근데|그런데|그리고|오히려|때문에|보니까)$/;for(const rawLine of src){const line=rawLine.trim();if(!line){if(out.length&&out[out.length-1]!=='')out.push('');continue;}let p=out.length-1;while(p>=0&&out[p]==='')p--;const prev=p>=0?out[p]:'';if(prev&&(dangling.test(prev)||bridge.test(prev)||frag.test(line))){out[p]=`${prev} ${line}`.trim();out.splice(p+1);continue;}out.push(line);}return out.join('\n').replace(/\n{3,}/g,'\n\n').trim();}
function normalizeParagraphs(text){const t=mergeAwkwardLineBreaks(text);if(!t)return t;const c=t.split('\n').map(x=>x.trim()).filter(Boolean);if(c.length<=3)return c.join('\n');if(/\n\s*\n/.test(t))return t;if(c.length===4)return `${c[0]}\n${c[1]}\n\n${c[2]}\n${c[3]}`;if(c.length===5)return `${c[0]}\n${c[1]}\n\n${c.slice(2).join('\n')}`;return c.join('\n');}
const reactionRE=/(?:ㅋㅋ+|ㅎㅎ+|ㅁㅊ|ㄷㄷ+|;;+|ㅠㅠ+|ㅜㅜ+|존맛탱|헐|와\b|아니\b|뭐야|미쳤|개맛|개웃|신박|반칙|못\s*참)/i;
function hasHook(text){const l=mergeAwkwardLineBreaks(text).split('\n').map(x=>x.trim()).filter(Boolean);if(!l.length)return false;const first=l.slice(0,2).join(' ');const hook=/(?:ㅋㅋ+|ㅁㅊ|ㄷㄷ+|;;+|존맛탱|미쳤|골\s*때리|뭐야|왜\s*이제|처음엔|아니|와\s|헐|신박|반칙|못\s*참|궁금|놀랐|이걸\s*이렇게|대박|선\s*넘|생각한\s*사람)/i;const curiosity=/(?:알고\s*보니|봤는데|보니까|열어봤|성분표|정체|비밀|핵심|문제|결과|이유|조합)/i;const dry=/^(?:가방에|버튼을?|뚜껑|제품은|이 제품|사용하면|재료는|만드는 법|특징은|기능은|들고 다니|보관|설거지|식단 관리|와인 안주로)/;if(hook.test(first)||curiosity.test(first))return true;if(dry.test(first))return false;return first.length<=32&&/[!?~]/.test(first);}
function rejectReasons(text){const t=mergeAwkwardLineBreaks(text),r=[],lines=t.split('\n').map(x=>x.trim()).filter(Boolean);if(!t)r.push('empty');if(lines.length<3||lines.length>10)r.push('line-count');if(lines.some(x=>x.length>52))r.push('long-line');if(!hasHook(t))r.push('weak-hook');if(!reactionRE.test(t))r.push('low-thread-reaction');if(lines.some(x=>/^(?:같아|같네|같음|ㅋㅋ+|ㅎㅎ+|ㅠ+|ㅜ+|ㄷㄷ+)$/i.test(x)))r.push('orphan-fragment');if(lines.some(x=>/^(?:매일|매번|요즘|그냥|진짜|그래서|근데|그런데|그리고|오히려|때문에|보니까)$/i.test(x)))r.push('orphan-bridge');if(/(?:입니다|합니다|됩니다|하세요|해보세요|추천드립니다|수 있습니다)/.test(t))r.push('formal-tone');if(/완전\s*짱|육즙(?:이)?\s*폭발|풍미|완벽한\s*조화|한층\s*더|매력적인|입맛을\s*사로잡|감칠맛을\s*더해/i.test(t))r.push('ai-review');if(/간편하게|활용도|실용적|효율적|편리하|장점(?:이야|이다)|포인트인\s*듯|확실히\s*다름|이래서\s*다들|다들\s*찾는|인기라(?:는|고)|인기\s*있는/i.test(t))r.push('product-copy');if(/(?:애들|엄마들|친구|남편|언니|주변\s*사람|다들).{0,45}(?:난리|바로\s*주문|사달|계속\s*해달|맛있다고|추천해줬|물어보|찾)/i.test(t))r.push('social-proof-story');if(/[가-힣]+냐(?=$|\s|[!?~ㅋㅎㅠㅜ])/m.test(t))r.push('nya-ending');if(/(?:했|됐|왔|갔|봤|먹었|썼|샀|좋았|괜찮았|편했|있었|없었|겠|있|없|좋|편)음(?=$|\s|[!?~ㅋㅎㅠㅜ])/m.test(t))r.push('generic-eumseum');if(/[가-힣]+더라(?:고|구|니까|며|면)?(?=$|\s|[!?~ㅋㅎㅠㅜ])/m.test(t))r.push('deora-experience');if(/눈여겨보는\s*중|두고\s*쓰는\s*중|계속\s*쓰는\s*중|요즘\s*이것만|매일\s*쓰는\s*중|먹는\s*중/i.test(t))r.push('invented-observer-experience');return [...new Set(r)];}
function isSoftLayoutOnly(reasons){return Array.isArray(reasons)&&reasons.length>0&&reasons.every(x=>x==='line-count'||x==='long-line');}
function promptFor(mode){const recipe=mode==='recipe';return `너는 한국 Threads 실제 사용자 말투로 글을 최종 편집한다\n광고 카피 블로그 후기처럼 쓰면 실패다\n\n[후킹]\n- 첫 1~2줄에 발견 반응 의외성 궁금증 중 하나를 반드시 만든다\n- 기능 설명부터 시작하지 않는다\n- 같은 후킹을 반복하지 않는다\n\n[Threads 반응언어 적극 사용]\n- 대부분의 글에는 자연스러운 Threads 반응표현을 최소 1개 넣어라\n- 후보: ㅋㅋ ㅋㅋㅋ ;; ㄷㄷ ㅁㅊ 헐 와 아니 ㅠㅠ ㅜㅜ 뭐야 개맛있음 존맛탱 미쳤네 신박하다\n- 한 글에 보통 1~2개만 사용하고 도배하지 마라\n- 음식에는 존맛탱 개맛있음 등을 문맥에 맞을 때 사용 가능\n- 신기하거나 충격적인 제품에는 ㄷㄷ ;; ㅁㅊ 등을 사용 가능\n- 웃기거나 어이없는 상황에는 ㅋㅋ ㅋㅋㅋ를 적극 사용\n- 아쉽거나 공감되는 상황에서만 ㅠㅠ ㅜㅜ를 사용\n- 표현을 아무 문맥에나 랜덤 삽입하지 말고 실제 감정과 맞춰라\n- ㅁㅊ과 존맛탱을 모든 글에 반복하지 마라\n\n[사람 말투]\n- 설명보다 즉각적인 반응을 우선한다\n- 확실히 다름 이래서 다들 찾는구나 같은 광고 평가문 금지\n- 다들 찾는다 인기다 난리다 같은 사회적 증거는 입력 근거 없으면 만들지 마라\n- ~더라 ~더라고 ~낫더라 ~좋더라 ~편하더라 금지\n- 직접 써봤다 먹어봤다 샀다 같은 경험을 새로 만들지 마라\n\n[줄바꿈]\n- 글자 수가 아니라 의미 단위로만 줄바꿈한다\n- 문장을 중간에서 자르지 않는다\n- 연결어 조사 부사만 혼자 한 줄에 두지 않는다\n- 3~6줄 우선\n- 1+2 2+1 2+2 1+3 등 자연스럽게 구성하고 고정 패턴 금지\n- 한 줄 최대 52자\n\n[금지]\n- 존댓말 ~냐 일반 음슴체 ~더라 계열\n- 문장 끝 마침표와 쉼표\n- 간편하게 활용도 실용적 효율적 편리하다 장점 포인트\n- ~하는 법 ~찾는다면 이거지 같은 광고 제목\n- 허구의 주변인 반응과 허구의 사용 경험\n${recipe?'- 레시피 핵심 재료와 조리 사실은 보존하고 가짜 비밀재료를 만들지 않는다\n- 필요하면 만드는 법은 댓글로 짧게 연결한다':'- 일반 상품은 억지 구매 권유 없이 짧은 반응으로 끝낸다'}\n\nJSON만 출력\n{"text":""}`;}
async function rewriteOnce(apiKey,currentText,mode,reasons){const res=await axios.post('https://api.openai.com/v1/chat/completions',{model:'gpt-4o-mini',temperature:0.92,max_tokens:900,response_format:{type:'json_object'},messages:[{role:'system',content:promptFor(mode)},{role:'user',content:`[현재 글]\n${currentText}\n\n[검수 실패]\n${reasons.join(', ')}\n\n걸린 부분만 자연스럽게 고쳐라\nlow-thread-reaction이면 문맥에 맞는 Threads 반응표현을 1~2개 자연스럽게 추가해라\nweak-hook이면 첫 1~2줄 후킹을 강화해라\n사실은 추가하지 마라`} ]},{headers:{Authorization:`Bearer ${apiKey}`,'content-type':'application/json'},timeout:30000});const raw=res.data?.choices?.[0]?.message?.content;const parsed=raw?JSON.parse(raw):{};return normalizeParagraphs(parsed.text||'');}
engine.buildThreadsFirstAutopilot=async function(accountId,args={}){const result=await originalBuild(accountId,args);if(!result?.text)return result;const current=normalizeParagraphs(result.text);const reasons=rejectReasons(current);if(reasons.length===0){console.log(`[AutopilotV3][HUMAN FINAL] v8 PASS-NO-REWRITE preview="${current.slice(0,160).replace(/\n/g,' / ')}"`);return {...result,text:current};}const key=getOpenAIKey(accountId);if(!key){if(isSoftLayoutOnly(reasons)){console.log(`[AutopilotV3][HUMAN FINAL] v8 SOFT-PASS no-key reasons=${reasons.join(',')} preview="${current.slice(0,160).replace(/\n/g,' / ')}"`);return {...result,text:current};}throw new Error(`[AUTOPILOT HUMAN TONE HARD REJECT] OpenAI key 없음 reasons=${reasons.join(',')}`);}try{const rewritten=await rewriteOnce(key,current,result.mode,reasons);const fixed=normalizeParagraphs(rewritten);const next=rejectReasons(fixed);console.log(`[AutopilotV3][HUMAN FINAL] v8 ONE-REWRITE reasons=${next.join(',')||'PASS'} preview="${fixed.slice(0,160).replace(/\n/g,' / ')}"`);if(fixed&&next.length===0)return {...result,text:fixed};if(fixed&&isSoftLayoutOnly(next)){console.log(`[AutopilotV3][HUMAN FINAL] v8 SOFT-PASS layout-only reasons=${next.join(',')}`);return {...result,text:fixed};}throw new Error(`[AUTOPILOT HUMAN TONE HARD REJECT] 1회 교정 후에도 실패 reasons=${next.join(',')||'unknown'}`);}catch(e){if(/AUTOPILOT HUMAN TONE HARD REJECT/.test(String(e.message||'')))throw e;console.warn(`[AutopilotV3][HUMAN FINAL] v8 rewrite error=${e.response?.data?.error?.message||e.message}`);if(isSoftLayoutOnly(reasons)){console.log(`[AutopilotV3][HUMAN FINAL] v8 SOFT-PASS rewrite-error layout-only reasons=${reasons.join(',')}`);return {...result,text:current};}throw new Error(`[AUTOPILOT HUMAN TONE HARD REJECT] 최종 말투 교정 호출 실패 reasons=${reasons.join(',')}`);}};
console.log('[AutopilotV3][HUMAN FINAL] v8 active-thread-reactions loaded · layout-only soft-pass');