const path = require('path');
const fs = require('fs');
const expressPath = require.resolve('express');
const realExpress = require('express');
let appInstance = null;
function wrappedExpress(...args) { appInstance = realExpress(...args); return appInstance; }
Object.assign(wrappedExpress, realExpress); require.cache[expressPath].exports = wrappedExpress;
require('./server');
if (!appInstance) throw new Error('Express app 초기화에 실패했습니다.');
const { db, getAccount, listAccounts, logUsage } = require('./db');
const videoEditor = require('./videoEditor');
const threadsMediaImporter = require('./threadsMediaImporter');
const { generateFromThreadsMaterial } = require('./threadsMaterialWriter');
const { listBenchmarkAccounts, addBenchmarkAccount, addBenchmarkAccountsBulk, deleteBenchmarkAccount, markUsedPost, collectBenchmarkMaterials, collectPostDetails } = require('./benchmarkAccounts');
try { db.exec(`ALTER TABLE posts ADD COLUMN recipe_comment_text TEXT`); } catch {}
try { db.exec(`ALTER TABLE posts ADD COLUMN media_items_json TEXT`); } catch {}
const uploadsDir = path.join(__dirname, 'uploads');
const videoEditLocks=new Set(), threadsImportLocks=new Set(), threadsSearchLocks=new Set();
function requireOwnedAccount(req,res,next){const accountId=Number(req.query.accountId||req.body?.accountId||req.params?.accountId);if(!accountId)return res.status(400).json({error:'accountId가 필요합니다'});const account=getAccount(accountId);if(!account)return res.status(404).json({error:'존재하지 않는 계정입니다'});if(!req.currentUser||account.user_id!==req.currentUser.id)return res.status(403).json({error:'본인 소유의 계정만 이용할 수 있습니다'});req.account=account;next();}
function requireAdmin(req,res,next){if(req.currentUser?.role!=='admin')return res.status(403).json({error:'관리자만 이용할 수 있습니다.'});next();}
function publicBaseUrl(req,account){if(account?.threads_redirect_uri){try{const u=new URL(account.threads_redirect_uri);return `${u.protocol}//${u.host}`;}catch{}}return `${req.protocol}://${req.get('host')}`;}
function ownVideoPath(accountId,filename){return path.join(uploadsDir,'videos',String(accountId),path.basename(String(filename||'')));}
function normalizeMediaItems(items){if(!Array.isArray(items))return[];const out=[];for(const item of items){const type=String(item?.type||'').toUpperCase();const url=String(item?.url||'').trim();if(!url||!['IMAGE','VIDEO'].includes(type))continue;if(!out.some(x=>x.type===type&&x.url===url))out.push({type,url});if(out.length>=10)break;}return out;}
function mediaBundleSentinel(items){return `__THREADS_MEDIA_BUNDLE__${encodeURIComponent(JSON.stringify(items))}`;}
appInstance.get('/api/threads/accounts',(req,res)=>{if(!req.currentUser)return res.status(401).json({error:'로그인이 필요합니다'});res.json({accounts:listAccounts(req.currentUser.id)});});
appInstance.get('/api/admin/benchmark-accounts',requireAdmin,(req,res)=>res.json({accounts:listBenchmarkAccounts()}));
appInstance.post('/api/admin/benchmark-accounts',requireAdmin,(req,res)=>{try{res.json({success:true,account:addBenchmarkAccount(req.body?.username)});}catch(err){res.status(400).json({error:err.message});}});
appInstance.post('/api/admin/benchmark-accounts/bulk',requireAdmin,(req,res)=>{try{const result=addBenchmarkAccountsBulk(req.body?.usernames||req.body?.text||'');res.json({success:true,...result});}catch(err){res.status(400).json({error:err.message});}});
appInstance.delete('/api/admin/benchmark-accounts/:id',requireAdmin,(req,res)=>{deleteBenchmarkAccount(req.params.id);res.json({success:true});});
appInstance.get('/api/threads/material-search',requireOwnedAccount,async(req,res)=>{if(threadsSearchLocks.has(req.account.id))return res.status(429).json({error:'이미 소재를 찾는 중입니다. 잠시 후 다시 시도해주세요.'});threadsSearchLocks.add(req.account.id);try{const items=await collectBenchmarkMaterials({limit:Number(req.query.limit)||12});res.json({success:true,items});}catch(err){console.error(`[material search] account #${req.account.id}:`,err.message);res.status(422).json({error:err.message||'소재를 찾지 못했습니다.'});}finally{threadsSearchLocks.delete(req.account.id);}});
appInstance.post('/api/threads/material-write',requireOwnedAccount,async(req,res)=>{const keyword=String(req.body?.keyword||'').trim(),sourceText=String(req.body?.sourceText||'').trim(),sourceUrl=String(req.body?.sourceUrl||'').trim(),username=String(req.body?.username||'').trim(),mode=req.body?.mode==='recipe'?'recipe':'product';if(!keyword&&!sourceText&&!sourceUrl)return res.status(400).json({error:'소재 내용이 필요합니다.'});try{let detailedText=sourceText,authorReplies='',sourceMedia={images:Array.isArray(req.body?.images)?req.body.images.filter(Boolean):[],videos:[],hasVideo:!!req.body?.hasVideo};if(sourceUrl&&username){try{const details=await collectPostDetails(sourceUrl,username);if(details?.sourceText&&details.sourceText.trim().length>=8)detailedText=details.sourceText.trim();if(Array.isArray(details?.authorReplies))authorReplies=details.authorReplies.filter(Boolean).join('\n\n');sourceMedia={images:Array.isArray(details?.images)?details.images.filter(Boolean):sourceMedia.images,videos:Array.isArray(details?.videos)?details.videos.filter(Boolean):[],hasVideo:!!details?.hasVideo};}catch(detailErr){console.warn(`[material detail fallback] ${sourceUrl}:`,detailErr.message);}}if(!detailedText&&keyword)detailedText=keyword;if(!detailedText)return res.status(422).json({error:'소재 본문을 확인하지 못했습니다. 다른 소재를 선택해주세요.'});const generated=await generateFromThreadsMaterial(req.account.id,{keyword,sourceText:detailedText,authorReplies,mode});if(req.currentUser?.id)logUsage(req.currentUser.id,'text');res.json({success:true,mode,sourceMedia,...generated});}catch(err){res.status(422).json({error:err.response?.data?.error?.message||err.message});}});
appInstance.post('/api/threads/material-post',requireOwnedAccount,(req,res)=>{const text=String(req.body?.text||'').trim(),scheduledAt=String(req.body?.scheduled_at||'').trim(),recipeCommentText=String(req.body?.recipe_comment_text||'').trim();if(!text||!scheduledAt)return res.status(400).json({error:'본문과 발행 예정 시각은 필수입니다.'});const mediaItems=normalizeMediaItems(req.body?.media_items);const imageList=mediaItems.filter(x=>x.type==='IMAGE').map(x=>x.url),videoList=mediaItems.filter(x=>x.type==='VIDEO').map(x=>x.url);let imageUrl=String(req.body?.image_url||'').trim()||null,extraImageUrl=String(req.body?.extra_image_url||'').trim()||null,videoUrl=String(req.body?.video_url||'').trim()||null;if(mediaItems.length===1){imageUrl=mediaItems[0].type==='IMAGE'?mediaItems[0].url:null;videoUrl=mediaItems[0].type==='VIDEO'?mediaItems[0].url:null;extraImageUrl=null;}else if(mediaItems.length>1){imageUrl=mediaBundleSentinel(mediaItems);extraImageUrl=null;videoUrl=null;}else{imageUrl=imageList[0]||imageUrl;extraImageUrl=imageList[1]||extraImageUrl;videoUrl=videoList[0]||videoUrl;}const link=String(req.body?.link||'').trim()||null,autoCommentEnabled=req.body?.auto_comment_enabled===false?0:1,commentStatus=(link||recipeCommentText)&&autoCommentEnabled?'pending':'none';const info=db.prepare(`INSERT INTO posts (account_id,text,link,image_url,extra_image_url,video_url,scheduled_at,auto_comment_enabled,comment_status,recipe_comment_text,media_items_json) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(req.account.id,text,link,imageUrl,extraImageUrl,videoUrl,scheduledAt,autoCommentEnabled,commentStatus,recipeCommentText||null,mediaItems.length?JSON.stringify(mediaItems):null);res.json({success:true,id:info.lastInsertRowid,mediaCount:mediaItems.length});});
appInstance.post('/api/threads/import',requireOwnedAccount,async(req,res)=>{const url=String(req.body?.url||'').trim();if(!url)return res.status(400).json({error:'Threads 게시물 URL을 입력해주세요.'});if(threadsImportLocks.has(req.account.id))return res.status(429).json({error:'이미 Threads 영상을 가져오는 중입니다.'});threadsImportLocks.add(req.account.id);try{const outputDir=path.join(uploadsDir,'videos',String(req.account.id));if(!fs.existsSync(outputDir))fs.mkdirSync(outputDir,{recursive:true});const result=await threadsMediaImporter.importThreadsVideo({url,outputDir});markUsedPost(url);const base=publicBaseUrl(req,req.account),publicUrl=`${base}/uploads/videos/${req.account.id}/${encodeURIComponent(result.filename)}`;res.json({success:true,filename:result.filename,url:publicUrl,mediaType:'video',size:result.size,sourceUrl:result.sourceUrl,poster:result.poster||null,title:result.title||''});}catch(err){res.status(422).json({error:err.message||'Threads 영상을 가져오지 못했습니다.'});}finally{threadsImportLocks.delete(req.account.id);}});
appInstance.post('/api/video/edit',requireOwnedAccount,async(req,res)=>{const filename=path.basename(String(req.body?.filename||''));if(!filename)return res.status(400).json({error:'편집할 영상 filename이 필요합니다.'});const inputPath=ownVideoPath(req.account.id,filename);if(!fs.existsSync(inputPath))return res.status(404).json({error:'편집할 영상 파일을 찾을 수 없습니다.'});if(videoEditLocks.has(req.account.id))return res.status(429).json({error:'이미 영상 편집 중입니다.'});videoEditLocks.add(req.account.id);try{const outputDir=path.join(uploadsDir,'videos',String(req.account.id));const result=await videoEditor.editVideo({inputPath,outputDir,start:req.body?.start,end:req.body?.end,mute:req.body?.mute!==false});const base=publicBaseUrl(req,req.account),publicUrl=`${base}/uploads/videos/${req.account.id}/${encodeURIComponent(result.filename)}`;res.json({success:true,filename:result.filename,url:publicUrl,mediaType:'video',size:result.size,sourceDuration:result.sourceDuration,start:result.start,end:result.end,duration:result.duration,muted:result.muted});}catch(err){res.status(422).json({error:err.message||'영상 편집에 실패했습니다.'});}finally{videoEditLocks.delete(req.account.id);}});
console.log('[Threads material] 소재 찾기 활성화');
