const engine=require('./autopilotMaterialEngine');
const benchmark=require('./benchmarkAccounts');
const axios=require('axios');
const previousBuild=engine.buildThreadsFirstAutopilot.bind(engine);
function clean(v){return String(v||'').replace(/\s+/g,' ').trim();}
function authorFromThreadsUrl(url){try{return decodeURIComponent(new URL(String(url||'')).pathname.match(/^\/@([^/]+)\/post\//i)?.[1]||'');}catch{return'';}}
function extractCoupangLinks(details){const out=[];for(const reply of(details?.authorReplies||[])){for(const raw of(String(reply||'').match(/https?:\/\/[^\s)\]}>,]+/gi)||[])){const u=raw.replace(/[.,;!?]+$/,'');if(/(?:^|\.)coupang\.com|link\.coupang\.com/i.test(u)&&!out.includes(u))out.push(u);}}return out.slice(0,8);}
function canonicalProductUrl(raw){try{const u=new URL(raw);if(!/(^|\.)coupang\.com$/i.test(u.hostname))return'';const m=u.pathname.match(/\/vp\/products\/(\d+)/i);if(!m)return'';const out=new URL(`https://www.coupang.com/vp/products/${m[1]}`);for(const k of['itemId','vendorItemId']){const v=u.searchParams.get(k);if(v)out.searchParams.set(k,v);}return out.toString();}catch{return'';}}
function productIdFromUrl(raw){try{const u=new URL(raw);return u.pathname.match(/\/vp\/products\/(\d+)/i)?.[1]||u.searchParams.get('productId')||'';}catch{return'';}}
function extractIds(s){const ids=new Set();for(const re of[/\/vp\/products\/(\d{5,})/gi,/[?&]productId=(\d{5,})/gi,/["']productId["']\s*[:=]\s*["']?(\d{5,})/gi,/productId%3D(\d{5,})/gi]){let m;while((m=re.exec(String(s||''))))ids.add(m[1]);}return[...ids];}
function saneTitle(t){t=clean(t).replace(/\s*[-|]\s*쿠팡!?\s*$/i,'').trim();if(t.length<3)return'';if(/^(쿠팡|coupang|로그인|로켓배송)$/i.test(t))return'';return t.slice(0,240);}
async function resolveOriginal(link){
 try{const r=await axios.get(link,{timeout:15000,maxRedirects:10,headers:{'user-agent':'Mozilla/5.0 (Linux; Android 15; SM-S938N) AppleWebKit/537.36 Chrome/140.0 Mobile Safari/537.36','accept-language':'ko-KR,ko;q=0.9'}});const final=String(r?.request?.res?.responseUrl||r?.request?._redirectable?._currentUrl||link),html=typeof r.data==='string'?r.data:'';const direct=canonicalProductUrl(final);const title=saneTitle(html.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i)?.[1]||html.match(/<title[^>]*>([^<]+)/i)?.[1]||'');if(direct){console.log(`[ORIGINAL COUPANG] HTTP 상품페이지 성공 title="${title||'-'}" productId=${productIdFromUrl(direct)}`);return{url:direct,name:title,sourceLink:link};}console.log(`[ORIGINAL COUPANG] HTTP shortlink 분석 final=${final} productIds=${extractIds(html).length}`);}catch(e){console.warn(`[ORIGINAL COUPANG] HTTP 분석 실패 reason="${e.message}"`);}
 const playwright=require('playwright');let browser,context;try{browser=await playwright.chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});context=await browser.newContext({locale:'ko-KR',viewport:{width:412,height:915},isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (Linux; Android 15; SM-S938N) AppleWebKit/537.36 Chrome/140.0 Mobile Safari/537.36'});const page=await context.newPage();page.setDefaultTimeout(22000);const urls=[];page.on('request',r=>urls.push(r.url()));page.on('response',r=>urls.push(r.url()));await page.goto(link,{waitUntil:'domcontentloaded',timeout:22000});await page.waitForTimeout(3000);
  // productId보다 사람이 보는 상품명을 먼저 찾는다.
  let info=await page.evaluate(()=>{const clean=s=>String(s||'').replace(/\s+/g,' ').trim();const sels=['meta[property="og:title"]','h1','[class*="prod-buy-header"] h2','[class*="product-title"]','[class*="ProductTitle"]','title'];let title='';for(const sel of sels){const el=document.querySelector(sel);const v=clean(el?.content||el?.innerText||el?.textContent||'');if(v.length>=3){title=v;break;}}const canonical=document.querySelector('link[rel="canonical"]')?.href||'';const hrefs=[...document.querySelectorAll('a[href]')].map(a=>a.href).filter(Boolean);return{title,canonical,hrefs,html:(document.documentElement?.innerHTML||'').slice(0,1200000)};}).catch(()=>({title:'',canonical:'',hrefs:[],html:''}));
  let title=saneTitle(info.title);let productUrl=canonicalProductUrl(page.url())||canonicalProductUrl(info.canonical);const evidence=[page.url(),info.canonical,...info.hrefs,...urls,info.html].join('\n');const ids=extractIds(evidence);if(!productUrl&&ids.length===1)productUrl=`https://www.coupang.com/vp/products/${ids[0]}`;
  // 단축페이지에서 상품 CTA가 하나면 실제로 눌러 최종 페이지의 제목을 다시 읽는다.
  if(!title||!productUrl){const cands=await page.locator('a[href],button').evaluateAll(els=>els.map((e,i)=>({i,href:e.href||'',text:String(e.innerText||e.textContent||'').replace(/\s+/g,' ').trim()})).filter(x=>/쿠팡|상품|구매|보러|열기|계속/i.test(x.text)||/coupang/i.test(x.href))).catch(()=>[]);if(cands.length===1){try{if(cands[0].href)await page.goto(cands[0].href,{waitUntil:'domcontentloaded',timeout:18000});else await page.locator('a[href],button').nth(cands[0].i).click();await page.waitForTimeout(2200);const meta=await page.evaluate(()=>({title:document.querySelector('meta[property="og:title"]')?.content||document.querySelector('h1')?.innerText||document.title||'',canonical:document.querySelector('link[rel="canonical"]')?.href||''}));title=saneTitle(meta.title)||title;productUrl=canonicalProductUrl(page.url())||canonicalProductUrl(meta.canonical)||productUrl;}catch{}}}
  if(title){console.log(`[ORIGINAL COUPANG] 원작성자 링크 상품명 확인 title="${title}" productId=${productIdFromUrl(productUrl)||'-'}`);return{url:productUrl||'',name:title,sourceLink:link,titleVerified:true};}
  if(productUrl){console.log(`[ORIGINAL COUPANG] 원작성자 상품URL 확인 productId=${productIdFromUrl(productUrl)}`);return{url:productUrl,name:'원본 작성자 선택 상품',sourceLink:link};}
  console.warn(`[ORIGINAL COUPANG] 원작성자 링크에서 상품명/상품URL 확인 실패 final=${page.url()}`);return null;
 }finally{if(context)try{await context.close();}catch{}if(browser)try{await browser.close();}catch{}}
}
engine.buildThreadsFirstAutopilot=async function(accountId,options){const result=await previousBuild(accountId,options);if(!result?.sourceUrl)return result;try{const username=authorFromThreadsUrl(result.sourceUrl),details=await benchmark.collectPostDetails(result.sourceUrl,username),links=extractCoupangLinks(details);if(!links.length){console.log(`[ORIGINAL COUPANG] 작성자 쿠팡 링크 없음 source=${result.sourceUrl}`);return result;}console.log(`[ORIGINAL COUPANG] 작성자 쿠팡 링크 ${links.length}개 발견 source=${result.sourceUrl}`);let p=null;for(const link of links){p=await resolveOriginal(link);if(p)break;}if(!p){console.warn('[ORIGINAL COUPANG] 원상품 확인 실패 → 기존 정확매칭 fallback');return result;}
 // 상품명이 확인되면 그것을 최우선 검색어로 넘긴다. URL까지 있으면 동일 URL을 그대로 딥링크 대상으로 사용한다.
 result.productSearchTerm=p.name;result.originalSellerProduct=p;result.originalSellerProductExact=!!p.url;if(p.url)result.product={...(result.product||{}),productId:productIdFromUrl(p.url)||result.product?.productId,name:p.name||result.product?.name,url:p.url,image:''};else result.product={...(result.product||{}),name:p.name||result.product?.name};console.log(`[ORIGINAL COUPANG] 원상품 우선 적용 title="${p.name}" productId=${productIdFromUrl(p.url)||'-'} url=${p.url||'(상품명 검색)'}`);
 }catch(e){console.warn(`[ORIGINAL COUPANG] 원상품 우선연결 실패 → 기존 정확매칭 fallback reason="${e.message}"`);}return result;};
console.log('[ORIGINAL COUPANG PATCH] 작성자 쿠팡링크 직접접속 → 상품명 우선확인 → productId/URL 보조확인 → 사용자 딥링크 적용');
