const axios=require('axios');
const{db,getAccount,getSystemApiSettings,getPexelsApiKey,getPixabayApiKey}=require('./db');
const youtubeApi=require('./youtubeApi');const coupangApi=require('./coupangApi');
const{searchFoodPhotos:searchPexels}=require('./pexelsApi');const{searchFoodPhotos:searchPixabay}=require('./pixabayApi');const{rankKeywordsByTrend}=require('./naverTrends');
const RECIPE_TOPICS=['비빔국수','김치찌개','된장찌개','제육볶음','닭볶음탕','떡볶이','계란볶음밥','김치볶음밥','오징어볶음','두부조림','감자조림','어묵볶음','진미채볶음','멸치볶음','양념계란','계란장','콩나물국','순두부찌개','냉면','비빔면','파스타','짜파게티 응용 레시피','라면 맛있게 끓이는 법','간장계란밥','닭갈비','고추장찌개','부대찌개','골뱅이무침','메밀국수','잔치국수','비빔밥','카레','마파두부','무생채','오이무침','깻잎무침','두부강정','감자채볶음','콩나물무침'];
const HIGH_INTENT=['참치액','연두','육수코인','냉면육수','쯔유','굴소스','멸치액젓','까나리액젓','맛술','미림','고추기름','치킨스톡','다시팩','비빔장','파스타소스','카레가루','들기름','다진마늘'];
function getOpenAIKey(id){const a=getAccount(id),s=getSystemApiSettings();return s.openai_api_key||process.env.OPENAI_API_KEY||a?.openai_api_key||null}
async function callOpenAI(id,system,user){const key=getOpenAIKey(id);if(!key)throw new Error('OpenAI API 키가 설정되지 않았습니다');const r=await axios.post('https://api.openai.com/v1/chat/completions',{model:'gpt-4o-mini',temperature:.82,max_tokens:1400,response_format:{type:'json_object'},messages:[{role:'system',content:system},{role:'user',content:user}]},{headers:{Authorization:`Bearer ${key}`,'content-type':'application/json'},timeout:30000});return JSON.parse(r.data.choices[0].message.content)}
function recent(){try{return db.prepare(`SELECT trend_note FROM posts ORDER BY id DESC LIMIT 24`).all().map(x=>String(x.trend_note||'')).join('|')}catch{return''}}
async function topicCandidates(id){const used=recent();let pool=RECIPE_TOPICS.filter(x=>!used.includes(x));if(pool.length<8)pool=RECIPE_TOPICS.slice();const c=pool.sort(()=>Math.random()-.5).slice(0,8);try{const r=await rankKeywordsByTrend(id,c);if(r?.length)return r.map(x=>({topic:x.keyword,trendNote:`네이버 데이터랩 레시피 트렌드 · ${x.keyword} (${x.avgRatio.toFixed(1)})`}));}catch(e){console.log('[Recipe][Trend] 데이터랩 실패:',e.message)}return c.map(x=>({topic:x,trendNote:`레시피형 · ${x}`}))}
async function video(id,topic,order){const key=getSystemApiSettings().youtube_api_key||process.env.YOUTUBE_API_KEY;if(!key)return null;try{return(await youtubeApi.searchVideos({apiKey:key,keyword:`${topic} 레시피`,order:order||'relevance',maxResults:5}))[0]||null}catch{return null}}
function normalizeServings(value){let s=String(value||'').trim().replace(/\s+/g,'');if(!s)return'2인분';if(/^\d+$/.test(s))return`${s}인분`;if(/^\d+[~\-]\d+$/.test(s))return`${s.replace('-','~')}인분`;if(/^\d+인$/.test(s))return`${s}분`;if(/^\d+[~\-]\d+인$/.test(s))return`${s.replace('-','~')}분`;if(/^\d+(?:~\d+)?인분$/.test(s))return s;const m=s.match(/(\d+)(?:[~\-](\d+))?/);return m?(m[2]?`${m[1]}~${m[2]}인분`:`${m[1]}인분`):'2인분'}
function sameIngredient(a,b){const x=String(a||'').replace(/\s+/g,'').toLowerCase(),y=String(b||'').replace(/\s+/g,'').toLowerCase();if(!x||!y)return false;if(x.includes(y)||y.includes(x))return true;const aliases=[['미림','맛술'],['멸치액젓','액젓'],['까나리액젓','액젓'],['멸치육수','멸치육수팩','다시팩'],['육수코인','코인육수']];return aliases.some(g=>g.some(v=>x.includes(v))&&g.some(v=>y.includes(v)))}
function ensureSecretInIngredients(r){const idx=r.ingredients.findIndex(x=>sameIngredient(x.name,r.secretIngredient));if(idx<0)throw new Error(`제휴 핵심재료가 실제 레시피 재료에 없음: ${r.secretIngredient}`);r.secretIngredient=r.ingredients[idx].name;r.coupangSearchKeyword=r.secretIngredient;return r}
function clean(d,f){const ingredients=(d.ingredients||[]).map(x=>({name:String(x.name||'').trim(),amount:String(x.amount||'').trim()})).filter(x=>x.name&&x.amount).slice(0,12);const o={dishName:String(d.dishName||f).trim(),servings:normalizeServings(d.servings),ingredients,optional:(d.optional||[]).slice(0,5),secretIngredient:String(d.secretIngredient||'').trim(),coupangSearchKeyword:String(d.coupangSearchKeyword||d.secretIngredient||'').trim(),hook:String(d.hook||'').trim()};if(!o.ingredients.length||!o.secretIngredient)throw new Error('레시피 AI 응답 부족');return ensureSecretInIngredients(o)}
async function generate(id,topic,v){const system=`한국 Threads 레시피 에디터. JSON만 출력. 정확한 재료/계량 중심. servings는 반드시 '2인분', '4인분', '2~3인분'처럼 인분까지 포함. 자연스러운 반말, 음슴체 금지. 매우 중요: secretIngredient는 ingredients 배열에 실제로 포함된 재료 중 하나만 선택해야 한다. ingredients에 없는 재료를 secretIngredient로 새로 만들면 안 된다. coupangSearchKeyword도 secretIngredient와 동일한 실제 재료를 사용한다. secretIngredient는 실제 음식에 자연스럽게 들어가면서 구매 전환이 가능한 차별화 재료를 고른다. 소금 설탕 물 후추 식용유 계란 양파 대파는 secretIngredient 금지, 일반 고추장 간장 참기름도 가능하면 피한다. ${HIGH_INTENT.join(' ')} 등을 실제 ingredients에 들어갈 때만 우선한다. 허위 사용경험 금지. JSON={"dishName":"","servings":"","hook":"","ingredients":[{"name":"","amount":""}],"optional":[],"secretIngredient":"","coupangSearchKeyword":""}`;return clean(await callOpenAI(id,system,`주제:${topic}\n참고:${v?.title||'없음'}`),topic)}
async function photos(recipe,topic){const queries=[recipe.dishName,topic].filter((q,i,a)=>q&&a.indexOf(q)===i);const pk=getPexelsApiKey()||process.env.PEXELS_API_KEY;if(pk)for(const q of queries){try{const p=await searchPexels({apiKey:pk,query:q,count:2});if(p.length>=2)return{photos:p.slice(0,2),source:'Pexels'};console.log(`[Recipe][Image] Pexels 정확사진 부족 ${p.length}/2 — ${q}`)}catch(e){console.log('[Recipe][Image] Pexels 실패:',e.message)}}const bk=getPixabayApiKey()||process.env.PIXABAY_API_KEY;if(bk)for(const q of queries){try{const p=await searchPixabay({apiKey:bk,query:q,count:2});if(p.length>=2)return{photos:p.slice(0,2),source:'Pixabay'};console.log(`[Recipe][Image] Pixabay 정확사진 부족 ${p.length}/2 — ${q}`)}catch(e){console.log('[Recipe][Image] Pixabay 실패:',e.message)}}return{photos:[],source:null}}
function post(r){return `${r.dishName} 해먹고 싶을 때\n재료 이것저것 찾기 귀찮아서\n필요한 것만 한 번에 보기 좋게 정리해봤어.\n\n재료랑 만드는 순서는 댓글에 적어둘게.`}
function comment(r){const ing=r.ingredients.slice(0,8).map(x=>`▪ ${x.name} ${x.amount}`).join('\n');return `✅ ${r.dishName} (${r.servings} 기준)\n\n${ing}\n\n재료 중에 ${r.secretIngredient} 뭐 사야 할지 찾기 귀찮은 사람 있을 것 같아서\n레시피에 들어가는 걸로 하나 골라놨어ㅋㅋ\n찾는 사람만 아래에서 봐👇`}
function keywordAliases(k){const key=String(k||'').trim();const groups=[['미림','맛술'],['멸치액젓','액젓'],['까나리액젓','액젓'],['멸치육수','멸치육수팩','다시팩','멸치다시팩'],['육수코인','코인육수'],['참치액','참치액젓']];for(const g of groups)if(g.some(x=>sameIngredient(x,key)))return g;return[key]}
function productMatchesKeyword(name,k){const n=String(name||'').replace(/\s+/g,'').toLowerCase();return keywordAliases(k).some(a=>n.includes(String(a).replace(/\s+/g,'').toLowerCase()))}
function score(p,k,i){const n=String(p.name||'').toLowerCase();let s=productMatchesKeyword(n,k)?80:0;s+=Math.max(0,12-i);if(p.rank)s+=Math.max(0,25-p.rank);if(p.isRocket)s+=8;if(/업소용|대용량|말통|식자재|10kg|12kg|14kg|15kg|18kg|20kg/.test(n))s-=45;return s}
async function product(id,k){const q=await coupangApi.searchProducts(id,k,12);const exact=q.map((p,i)=>({p,i,score:score(p,k,i)})).filter(x=>productMatchesKeyword(x.p.name,k)).sort((a,b)=>b.score-a.score);if(!exact.length)throw new Error(`쿠팡 정확매칭 상품 없음: ${k}`);const picked=exact[0].p;if(!productMatchesKeyword(picked.name,k))throw new Error(`쿠팡 상품 불일치: 핵심재료=${k}, 상품=${picked.name}`);return picked}
async function buildRecipeAutopilot({account,target}){const candidates=await topicCandidates(account.id);let lastError=null;for(const picked of candidates.slice(0,6)){try{console.log(`[Recipe] 사진 필수 레시피 시도 — 주제="${picked.topic}"`);const v=await video(account.id,picked.topic,account.autopilot_youtube_order);const r=await generate(account.id,picked.topic,v);const img=await photos(r,picked.topic);if(img.photos.length<2){console.log(`[Recipe][Image] "${picked.topic}" 정확한 음식사진 2장 미확보 → 다음 후보`);continue}const p=await product(account.id,r.coupangSearchKeyword);console.log(`[Recipe] 최종 선택 주제="${picked.topic}" 핵심재료="${r.secretIngredient}" 이미지=${img.source} ${img.photos.length}장 상품="${p.name}"`);return{text:post(r),recipeCommentText:comment(r),link:p.url,imageUrl:img.photos[0].imageUrl,extraImageUrl:img.photos[1].imageUrl,imageSourceLabel:`${img.source} 요리사진 2장`,product:p,keyword:r.coupangSearchKeyword,trendNote:picked.trendNote,recipe:r,youtubeSource:v,target}}catch(e){lastError=e;console.log(`[Recipe] 후보 실패 "${picked.topic}" → 다음 후보: ${e.message}`)}}throw new Error(`유효한 핵심재료·정확한 쿠팡 상품·음식사진 2장이 있는 레시피를 찾지 못했습니다${lastError?`: ${lastError.message}`:''}`)}
module.exports={buildRecipeAutopilot};