const axios=require('axios');
const{db,getAccount,getSystemApiSettings,getPexelsApiKey,getPixabayApiKey}=require('./db');
const youtubeApi=require('./youtubeApi');const coupangApi=require('./coupangApi');
const{searchFoodPhotos:searchPexels}=require('./pexelsApi');const{searchFoodPhotos:searchPixabay}=require('./pixabayApi');const{rankKeywordsByTrend}=require('./naverTrends');
const FALLBACK_RECIPE_TOPICS=['비빔국수','김치찌개','된장찌개','제육볶음','닭볶음탕','떡볶이','계란볶음밥','김치볶음밥','오징어볶음','두부조림','감자조림','어묵볶음','진미채볶음','멸치볶음','양념계란','계란장','콩나물국','순두부찌개','냉면','비빔면','파스타','짜파게티 응용 레시피','라면 맛있게 끓이는 법','간장계란밥','닭갈비','고추장찌개','부대찌개','골뱅이무침','메밀국수','잔치국수','비빔밥','카레','마파두부','무생채','오이무침','깻잎무침','두부강정','감자채볶음','콩나물무침'];
const HIGH_INTENT=['참치액','연두','육수코인','냉면육수','쯔유','굴소스','멸치액젓','까나리액젓','맛술','미림','고추기름','치킨스톡','다시팩','비빔장','파스타소스','카레가루','들기름','다진마늘'];
const LOW_VALUE_SECRET=/^(소금|설탕|물|후추|식용유|계란|달걀|양파|대파)$/;
const EXCLUDED_PRODUCT_RE=/사료|간식|영양제|건강기능식품|보호대|장난감|세정제|세제|샴푸|화장품|비누|기계|도구|커터|슬라이서|분쇄기|다지기|보관용기|용기/i;
const ALIAS_GROUPS=[['미림','맛술','요리술'],['멸치액젓','액젓','멸치액'],['까나리액젓','액젓'],['멸치육수','멸치육수팩','다시팩','멸치다시팩','육수팩'],['육수코인','코인육수','한알육수'],['참치액','참치액젓','참치액기스'],['굴소스','오이스터소스','oyster sauce'],['다진마늘','간마늘','다진 마늘'],['국간장','조선간장','한식간장'],['진간장','양조간장'],['치킨스톡','치킨스톡분말','치킨스톡큐브'],['쯔유','츠유','메밀장국'],['비빔장','비빔소스','비빔국수양념'],['파스타소스','스파게티소스','토마토파스타소스'],['카레가루','카레분말','카레'],['들기름','들깨기름']];
function getOpenAIKey(id){const a=getAccount(id),s=getSystemApiSettings();return s.openai_api_key||process.env.OPENAI_API_KEY||a?.openai_api_key||null}
async function callOpenAI(id,system,user){const key=getOpenAIKey(id);if(!key)throw new Error('OpenAI API 키가 설정되지 않았습니다');const r=await axios.post('https://api.openai.com/v1/chat/completions',{model:'gpt-4o-mini',temperature:.82,max_tokens:1400,response_format:{type:'json_object'},messages:[{role:'system',content:system},{role:'user',content:user}]},{headers:{Authorization:`Bearer ${key}`,'content-type':'application/json'},timeout:30000});return JSON.parse(r.data.choices[0].message.content)}
async function visionCheck(id,dish,imageUrl){const key=getOpenAIKey(id);if(!key)return{accept:false,reason:'OpenAI API 키 없음'};try{const r=await axios.post('https://api.openai.com/v1/chat/completions',{model:'gpt-4o-mini',temperature:0,max_tokens:180,response_format:{type:'json_object'},messages:[{role:'system',content:'너는 음식 사진 검수기다. 매우 보수적으로 판정한다. 목표 음식과 실제 사진이 명확히 같은 완성요리일 때만 accept=true. 식물 재배사진, 생재료, 포장제품, 조리 전 재료, 다른 음식, 비슷하지만 다른 요리, 음식인지 불명확한 사진은 모두 false. JSON만 출력: {"accept":true/false,"confidence":0-100,"reason":"짧은 한국어 이유"}'},{role:'user',content:[{type:'text',text:`목표 음식: ${dish}\n이 사진이 실제 완성된 '${dish}' 요리 사진인지 판정해. 확신이 높을 때만 승인해.`},{type:'image_url',image_url:{url:imageUrl,detail:'low'}}]}]},{headers:{Authorization:`Bearer ${key}`,'content-type':'application/json'},timeout:30000});const d=JSON.parse(r.data.choices[0].message.content);const confidence=Number(d.confidence)||0;return{accept:d.accept===true&&confidence>=80,confidence,reason:String(d.reason||'')}}catch(e){console.log(`[Recipe][Vision] 검수 실패 — ${dish}: ${e.message}`);return{accept:false,confidence:0,reason:`검수 API 실패: ${e.message}`}}}
async function validatePhotos(id,dish,candidates){const approved=[];for(const p of candidates){if(!p?.imageUrl)continue;const v=await visionCheck(id,dish,p.imageUrl);console.log(`[Recipe][Vision] ${v.accept?'승인':'거절'} dish="${dish}" confidence=${v.confidence} source=${p.source||'-'} reason="${v.reason}"`);if(v.accept)approved.push(p);if(approved.length>=2)break}return approved}
function recent(){try{return db.prepare(`SELECT trend_note FROM posts ORDER BY id DESC LIMIT 24`).all().map(x=>String(x.trend_note||'')).join('|')}catch{return''}}
async function generateTopicPool(accountId){const used=recent();const system=`너는 한국 Threads용 레시피 주제 기획자다. JSON만 출력한다. 찌개/국물요리, 볶음/조림, 면요리, 밥요리, 에어프라이어/오븐요리, 간단 브런치, 술안주, 다이어트/저칼로리식, 분식, 디저트/베이킹, 아시아 퓨전요리(월남쌈, 마라 등), 자취생 원팬요리 등에서 최소 6개 이상 카테고리를 섞어서 서로 다른 요리 주제 15개를 만들어라. 너무 어렵거나 재료 구하기 힘든 요리는 제외하고, Threads에서 반응 좋을 법한 실생활 밀착형 요리 위주로 만든다. 최근에 다룬 주제와 겹치지 않게 한다. JSON={"topics":["주제1","주제2",...]} 형식으로만 출력한다.`;try{const d=await callOpenAI(accountId,system,`최근에 다룬 주제/기록:\n${used||'없음'}\n\n새로운 레시피 주제 15개를 만들어줘.`);const topics=Array.isArray(d?.topics)?d.topics.map(x=>String(x||'').trim()).filter(Boolean):[];const unique=[...new Set(topics)];console.log(`[Recipe][TopicAI] 신규 주제 ${unique.length}개 생성`);return unique.slice(0,15)}catch(e){console.log(`[Recipe][TopicAI] 생성 실패 — 폴백 사용: ${e.message}`);return[]}}
async function topicCandidates(id){const used=recent();let pool=await generateTopicPool(id);pool=pool.filter(x=>!used.includes(x));if(pool.length<8){const fallback=FALLBACK_RECIPE_TOPICS.filter(x=>!used.includes(x)&&!pool.includes(x));pool=[...pool,...fallback.slice(0,8-pool.length)]}if(pool.length<8){for(const x of FALLBACK_RECIPE_TOPICS){if(!pool.includes(x))pool.push(x);if(pool.length>=8)break}}const c=[...new Set(pool)].sort(()=>Math.random()-.5).slice(0,8);try{const r=await rankKeywordsByTrend(id,c);if(r?.length)return r.map(x=>({topic:x.keyword,trendNote:`네이버 데이터랩 레시피 트렌드 · ${x.keyword} (${x.avgRatio.toFixed(1)})`}));}catch(e){console.log('[Recipe][Trend] 데이터랩 실패:',e.message)}return c.map(x=>({topic:x,trendNote:`레시피형 · ${x}`}))}
async function video(id,topic,order){const key=getSystemApiSettings().youtube_api_key||process.env.YOUTUBE_API_KEY;if(!key)return null;try{return(await youtubeApi.searchVideos({apiKey:key,keyword:`${topic} 레시피`,order:order||'relevance',maxResults:5}))[0]||null}catch{return null}}
function normalizeServings(value){let s=String(value||'').trim().replace(/\s+/g,'');if(!s)return'2인분';if(/^\d+$/.test(s))return`${s}인분`;if(/^\d+[~\-]\d+$/.test(s))return`${s.replace('-','~')}인분`;if(/^\d+인$/.test(s))return`${s}분`;if(/^\d+[~\-]\d+인$/.test(s))return`${s.replace('-','~')}분`;if(/^\d+(?:~\d+)?인분$/.test(s))return s;const m=s.match(/(\d+)(?:[~\-](\d+))?/);return m?(m[2]?`${m[1]}~${m[2]}인분`:`${m[1]}인분`):'2인분'}
function norm(v){return String(v||'').replace(/\s+/g,'').toLowerCase()}
function aliasesFor(k){const key=String(k||'').trim();const nk=norm(key);for(const g of ALIAS_GROUPS)if(g.some(x=>{const nx=norm(x);return nk===nx||nk.includes(nx)||nx.includes(nk)}))return [...new Set([key,...g])];return[key]}
function sameIngredient(a,b){const x=norm(a),y=norm(b);if(!x||!y)return false;if(x.includes(y)||y.includes(x))return true;return aliasesFor(a).some(v=>aliasesFor(b).some(w=>{const nv=norm(v),nw=norm(w);return nv===nw||nv.includes(nw)||nw.includes(nv)}))}
function chooseFallbackSecret(ingredients,requested){const exact=ingredients.find(x=>sameIngredient(x.name,requested));if(exact)return exact.name;for(const hi of HIGH_INTENT){const found=ingredients.find(x=>sameIngredient(x.name,hi)&&!LOW_VALUE_SECRET.test(x.name));if(found)return found.name}const useful=ingredients.find(x=>!LOW_VALUE_SECRET.test(x.name));return useful?.name||ingredients[0]?.name||''}
function clean(d,f){const ingredients=(d.ingredients||[]).map(x=>({name:String(x.name||'').trim(),amount:String(x.amount||'').trim()})).filter(x=>x.name&&x.amount).slice(0,12);if(!ingredients.length)throw new Error('레시피 AI 응답 부족');const steps=Array.isArray(d.steps)?d.steps.map(x=>String(x||'').trim()).filter(Boolean).slice(0,6):[];const requested=String(d.secretIngredient||d.coupangSearchKeyword||'').trim();const secretIngredient=chooseFallbackSecret(ingredients,requested);if(!secretIngredient)throw new Error('제휴 핵심재료를 선택할 수 없습니다');if(requested&&!sameIngredient(requested,secretIngredient))console.log(`[Recipe] AI 핵심재료 보정 "${requested}" → "${secretIngredient}"`);return{dishName:String(d.dishName||f).trim(),servings:normalizeServings(d.servings),ingredients,optional:(d.optional||[]).slice(0,5),steps,secretIngredient,coupangSearchKeyword:secretIngredient,hook:String(d.hook||'').trim()}}
async function generate(id,topic,v){const system=`한국 Threads 레시피 에디터. JSON만 출력. 정확한 재료/계량 중심. servings는 반드시 '2인분', '4인분', '2~3인분'처럼 인분까지 포함. 자연스러운 반말, 음슴체 금지. steps는 실제로 따라할 수 있는 구체적인 조리 순서 3~6단계로 만들고, 각 단계는 한 문장으로 작성한다. 매우 중요: secretIngredient는 ingredients 배열에 실제로 포함된 재료 중 하나만 선택해야 한다. ingredients에 없는 재료를 secretIngredient로 새로 만들면 안 된다. coupangSearchKeyword도 secretIngredient와 동일한 실제 재료를 사용한다. secretIngredient는 실제 음식에 자연스럽게 들어가면서 구매 전환이 가능한 차별화 재료를 고른다. 소금 설탕 물 후추 식용유 계란 양파 대파는 secretIngredient 금지, 일반 고추장 간장 참기름도 가능하면 피한다. ${HIGH_INTENT.join(' ')} 등을 실제 ingredients에 들어갈 때만 우선한다. 허위 사용경험 금지. JSON={"dishName":"","servings":"","hook":"","ingredients":[{"name":"","amount":""}],"optional":[],"steps":["조리 순서 1","조리 순서 2","조리 순서 3"],"secretIngredient":"","coupangSearchKeyword":""}`;return clean(await callOpenAI(id,system,`주제:${topic}\n참고:${v?.title||'없음'}`),topic)}
async function photos(id,recipe,topic){const queries=[recipe.dishName,topic].filter((q,i,a)=>q&&a.indexOf(q)===i);let bestSingle=null;const pk=getPexelsApiKey()||process.env.PEXELS_API_KEY;if(pk)for(const q of queries){try{const p=await searchPexels({apiKey:pk,query:q,count:8});const ok=await validatePhotos(id,recipe.dishName,p);if(ok.length>=2)return{photos:ok.slice(0,2),source:'Pexels+Vision'};if(ok.length===1&&!bestSingle)bestSingle={photos:ok.slice(0,1),source:'Pexels+Vision'};console.log(`[Recipe][Image] Pexels Vision 승인 ${ok.length}장 — ${q}`)}catch(e){console.log('[Recipe][Image] Pexels 실패:',e.message)}}const bk=getPixabayApiKey()||process.env.PIXABAY_API_KEY;if(bk)for(const q of queries){try{const p=await searchPixabay({apiKey:bk,query:q,count:8});const ok=await validatePhotos(id,recipe.dishName,p);if(ok.length>=2)return{photos:ok.slice(0,2),source:'Pixabay+Vision'};if(ok.length===1&&!bestSingle)bestSingle={photos:ok.slice(0,1),source:'Pixabay+Vision'};console.log(`[Recipe][Image] Pixabay Vision 승인 ${ok.length}장 — ${q}`)}catch(e){console.log('[Recipe][Image] Pixabay 실패:',e.message)}}if(bestSingle){console.log('[Recipe][Image] Vision 승인 1장 확보 — 1장 게시로 진행');return bestSingle}return{photos:[],source:null}}
function post(r){const ingredients=r.ingredients.map(x=>`* ${x.name} ${x.amount}`).join('\n');const steps=Array.isArray(r.steps)?r.steps.filter(Boolean):[];const cooking=steps.length?`\n\n✅ 만드는 법\n${steps.map((s,i)=>`${i+1}. ${s}`).join('\n')}`:'';return `✅ ${r.dishName} (${r.servings} 기준)\n\n${ingredients}${cooking}\n\n🔎 재료 뭐 살지 고민되면 댓글👇`}
function comment(r){const ing=r.ingredients.slice(0,8).map(x=>`▪ ${x.name} ${x.amount}`).join('\n');return `✅ ${r.dishName} (${r.servings} 기준)\n\n${ing}\n\n재료 중에 ${r.secretIngredient} 뭐 사야 할지 찾기 귀찮은 사람 있을 것 같아서\n레시피에 들어가는 걸로 하나 골라놨어ㅋㅋ\n찾는 사람만 아래에서 봐👇`}
function productMatchesKeyword(name,k){const n=norm(name);return aliasesFor(k).some(a=>{const x=norm(a);return x&&n.includes(x)})}
function isExcludedProduct(p){return EXCLUDED_PRODUCT_RE.test(String(p?.name||''))}
function score(p,k,i){const n=String(p.name||'').toLowerCase();let s=productMatchesKeyword(n,k)?80:0;s+=Math.max(0,15-i);if(p.rank)s+=Math.max(0,25-p.rank);if(p.isRocket)s+=8;if(/업소용|대용량|말통|식자재|10kg|12kg|14kg|15kg|18kg|20kg/.test(n))s-=45;return s}
async function aiPickProduct(id,ingredient,results){if(!results.length)return null;try{const list=results.slice(0,8).map((p,i)=>`${i}: ${p.name}`).join('\n');const d=await callOpenAI(id,'너는 쿠팡 식재료 상품 매칭 검수기다. 사용자가 요리에 넣을 식재료와 검색 결과 상품명이 주어진다. 해당 식재료로 실제 사용할 수 있는 상품만 고른다. 엉뚱한 완제품 요리, 조리도구, 건강기능식품, 반려동물용품은 고르지 않는다. 브랜드명이나 표기가 달라도 같은 식재료면 허용한다. JSON만 출력: {"index":숫자 또는 -1,"confidence":0-100,"reason":"짧은 이유"}',`필요한 식재료: ${ingredient}\n상품 후보:\n${list}`);const idx=Number(d.index);const confidence=Number(d.confidence)||0;if(Number.isInteger(idx)&&idx>=0&&idx<results.length&&confidence>=65){console.log(`[Recipe][Coupang][AI] 승인 ingredient="${ingredient}" confidence=${confidence} product="${results[idx].name}"`);return results[idx]}console.log(`[Recipe][Coupang][AI] 적합 상품 없음 ingredient="${ingredient}" confidence=${confidence}`)}catch(e){console.log(`[Recipe][Coupang][AI] 검수 실패 ingredient="${ingredient}": ${e.message}`)}return null}
async function searchProductFlexible(id,k){let results;try{results=await coupangApi.searchProducts(id,k,10)}catch(e){if(coupangApi.isRateLimitError?.(e))throw e;console.log(`[Recipe][Coupang] 검색 실패 keyword="${k}": ${e.message}`);return null}if(!results.length)return null;const safeResults=results.filter(p=>!isExcludedProduct(p));const excludedCount=results.length-safeResults.length;if(excludedCount)console.log(`[Recipe][Coupang] 제외상품 ${excludedCount}개 필터링 ingredient="${k}"`);if(!safeResults.length)return null;const ranked=safeResults.map((p,i)=>({p,i,score:score(p,k,i)})).filter(x=>productMatchesKeyword(x.p.name,k)&&!isExcludedProduct(x.p)).sort((a,b)=>b.score-a.score);if(ranked.length){console.log(`[Recipe][Coupang] 문자매칭 성공 ingredient="${k}" product="${ranked[0].p.name}"`);return ranked[0].p}const aiPicked=await aiPickProduct(id,k,safeResults);if(aiPicked&&!isExcludedProduct(aiPicked))return aiPicked;return null}
function ingredientCandidates(r){const names=r.ingredients.map(x=>x.name).filter(Boolean);const preferred=[];const push=k=>{if(!k||LOW_VALUE_SECRET.test(String(k).trim()))return;if(!preferred.some(x=>sameIngredient(x,k)))preferred.push(k)};push(r.secretIngredient);for(const hi of HIGH_INTENT){const found=names.find(n=>sameIngredient(n,hi));if(found)push(found)}for(const n of names)push(n);return preferred.slice(0,2)}
async function findAffiliateProduct(id,r){const candidates=ingredientCandidates(r);for(const ingredient of candidates){const p=await searchProductFlexible(id,ingredient);if(p){const actual=r.ingredients.find(x=>sameIngredient(x.name,ingredient))?.name||ingredient;r.secretIngredient=actual;r.coupangSearchKeyword=actual;return p}console.log(`[Recipe][Coupang] 상품 없음 — 다음 재료 시도: ${ingredient}`)}throw new Error(`쿠팡 매칭 상품 없음(최대 2회 검색): ${candidates.join(' / ')}`)}
async function buildRecipeAutopilot({account,target}){const cooldown=coupangApi.getApiCooldown?.(account.id);if(cooldown){const e=new Error(`쿠팡 API cooldown 중: ${cooldown.cooldown_until}`);e.code='COUPANG_RATE_LIMIT';e.isCoupangRateLimit=true;throw e}const candidates=await topicCandidates(account.id);let lastError=null;for(const picked of candidates.slice(0,6)){try{console.log(`[Recipe] 레시피 검수 시도 — 주제="${picked.topic}"`);const v=await video(account.id,picked.topic,account.autopilot_youtube_order);const r=await generate(account.id,picked.topic,v);const p=await findAffiliateProduct(account.id,r);console.log(`[Recipe] 쿠팡 핵심재료 확정 — ${r.secretIngredient} / 상품="${p.name}"`);const img=await photos(account.id,r,picked.topic);if(img.photos.length<1){console.log(`[Recipe][Image] "${picked.topic}" Vision 통과 음식사진 없음 → 다음 후보`);continue}const photoCount=img.photos.length;console.log(`[Recipe] 최종 선택 주제="${picked.topic}" 핵심재료="${r.secretIngredient}" 이미지=${img.source} ${photoCount}장 상품="${p.name}"`);return{text:post(r),recipeCommentText:comment(r),link:p.url,imageUrl:img.photos[0].imageUrl,extraImageUrl:img.photos[1]?.imageUrl||null,imageSourceLabel:`${img.source} 요리사진 ${photoCount}장`,product:p,keyword:r.coupangSearchKeyword,trendNote:picked.trendNote,recipe:r,youtubeSource:v,target}}catch(e){if(coupangApi.isRateLimitError?.(e))throw e;lastError=e;console.log(`[Recipe] 후보 실패 "${picked.topic}" → 다음 후보: ${e.message}`)}}throw new Error(`유효한 핵심재료·쿠팡 상품·Vision 통과 음식사진이 있는 레시피를 찾지 못했습니다${lastError?`: ${lastError.message}`:''}`)}
module.exports={buildRecipeAutopilot};