const axios = require('axios');
const { db, getAccount, getSystemApiSettings, getPexelsApiKey } = require('./db');
const youtubeApi = require('./youtubeApi');
const coupangApi = require('./coupangApi');
const { searchFoodPhotos } = require('./pexelsApi');
const { rankKeywordsByTrend } = require('./naverTrends');

const RECIPE_TOPICS = [
  '비빔국수','김치찌개','된장찌개','제육볶음','닭볶음탕','떡볶이','계란볶음밥','김치볶음밥','오징어볶음','두부조림',
  '감자조림','어묵볶음','진미채볶음','멸치볶음','양념계란','계란장','콩나물국','순두부찌개','냉면','비빔면','파스타',
  '짜파게티 응용 레시피','라면 맛있게 끓이는 법','간장계란밥','닭갈비','고추장찌개','부대찌개','골뱅이무침','메밀국수',
  '잔치국수','비빔밥','카레','마파두부','무생채','오이무침','깻잎무침','두부강정','감자채볶음','콩나물무침'
];
const POST_STYLES=['problem','difference','simple','ratio','ingredient','leftover'];
const LINK_LEADS=[
  '이 재료 찾는 사람 있을까 봐 아래에만 남겨둘게👇',
  '이 레시피에 쓸 거 찾는 사람만 아래에서 봐👇',
  '이거 뭐 쓰는지 궁금한 사람 있을 것 같아서 아래에 남겨둘게👇',
  '이 재료는 하나 골라놨어. 필요한 사람만 아래에서 봐👇',
  '이건 은근 아무거나 고르기 애매해서 괜찮은 걸로 하나 골라놨어👇'
];
const BORING_SECRET = ['소금','설탕','물','후추','식용유','밀가루','계란','대파','양파','고추장','간장','참기름'];
const HIGH_INTENT = ['참치액','연두','육수코인','냉면육수','쯔유','굴소스','멸치액젓','까나리액젓','맛술','고추기름','치킨스톡','다시팩','비빔장','파스타소스','카레가루','들기름','다진마늘'];

function getOpenAIKey(accountId){const account=getAccount(accountId);const shared=getSystemApiSettings();return shared.openai_api_key||process.env.OPENAI_API_KEY||account?.openai_api_key||null;}
async function callOpenAI(accountId,system,user,maxTokens=1400){const apiKey=getOpenAIKey(accountId);if(!apiKey)throw new Error('OpenAI API 키가 설정되지 않았습니다');const res=await axios.post('https://api.openai.com/v1/chat/completions',{model:'gpt-4o-mini',temperature:0.82,max_tokens:maxTokens,response_format:{type:'json_object'},messages:[{role:'system',content:system},{role:'user',content:user}]},{headers:{Authorization:`Bearer ${apiKey}`,'content-type':'application/json'},timeout:30000});const raw=res.data?.choices?.[0]?.message?.content?.trim();if(!raw)throw new Error('레시피 AI 결과를 받지 못했습니다');return JSON.parse(raw);}
function pickOne(list){return list[Math.floor(Math.random()*list.length)];}
function recentRecipeNames(){try{return db.prepare(`SELECT trend_note FROM posts WHERE trend_note LIKE '레시피형 · %' ORDER BY id DESC LIMIT 18`).all().map(r=>String(r.trend_note||'').replace('레시피형 · ','').trim()).filter(Boolean);}catch{return [];}}
async function pickRecipeTopic(accountId){const recent=new Set(recentRecipeNames());let pool=RECIPE_TOPICS.filter(x=>!recent.has(x));if(pool.length<5)pool=RECIPE_TOPICS.slice();const shuffled=pool.sort(()=>Math.random()-0.5);const candidates=shuffled.slice(0,5);try{const ranked=await rankKeywordsByTrend(accountId,candidates);if(ranked?.length){const top=ranked[0];console.log(`[Recipe][Trend] 네이버 데이터랩 선택 — ${top.keyword} (최근3일 평균 ${top.avgRatio.toFixed(1)}) / 후보=${candidates.join(', ')}`);return {topic:top.keyword,trendNote:`네이버 데이터랩 레시피 트렌드 · ${top.keyword} (${top.avgRatio.toFixed(1)})`};}}catch(err){console.log('[Recipe][Trend] 데이터랩 실패 — 랜덤 폴백:',err.response?.data||err.message);}const topic=pickOne(candidates);return {topic,trendNote:`레시피형 · ${topic}`};}
async function findRecipeVideo(accountId,topic,order='relevance'){const shared=getSystemApiSettings();const apiKey=shared.youtube_api_key||process.env.YOUTUBE_API_KEY;if(!apiKey)return null;for(const q of [`${topic} 레시피`,`${topic} 황금레시피`,`${topic} 밥도둑`]){try{const list=await youtubeApi.searchVideos({apiKey,keyword:q,order,maxResults:10});if(list.length)return list[0];}catch(err){console.log(`[Recipe] YouTube 검색 실패 "${q}":`,err.response?.data?.error?.message||err.message);}}return null;}
async function findRecipePhotos(recipe,topic){const apiKey=getPexelsApiKey()||process.env.PEXELS_API_KEY;if(!apiKey){console.log('[Recipe] Pexels API Key 없음 — 관리자 페이지에서 키를 저장해주세요');return [];}for(const query of [recipe.dishName,topic,`${recipe.dishName} korean food`]){try{const photos=await searchFoodPhotos({apiKey,query,count:2});if(photos.length){console.log(`[Recipe] Pexels 요리사진 ${photos.length}장 선택 — query="${query}"`);return photos.slice(0,2);}}catch(err){console.log(`[Recipe] Pexels 이미지 검색 실패 "${query}":`,err.response?.data?.error||err.message);}}return [];}
function sanitizeRecipeJson(data,fallbackDish){const ingredients=Array.isArray(data.ingredients)?data.ingredients.map(x=>({name:String(x?.name||'').trim(),amount:String(x?.amount||'').trim()})).filter(x=>x.name&&x.amount).slice(0,12):[];const optional=Array.isArray(data.optional)?data.optional.map(x=>String(x||'').trim()).filter(Boolean).slice(0,6):[];const dishName=String(data.dishName||fallbackDish||'오늘의 요리').trim();const servings=String(data.servings||'1~2인분').trim();const secretIngredient=String(data.secretIngredient||'').trim();const coupangSearchKeyword=String(data.coupangSearchKeyword||secretIngredient||'').trim();const hook=String(data.hook||'').trim();const secretReason=String(data.secretReason||'').trim();const tastePoint=String(data.tastePoint||'').trim();if(!ingredients.length||!secretIngredient||!coupangSearchKeyword)throw new Error('레시피 AI 응답 필수 항목이 부족합니다');return{dishName,servings,ingredients,optional,secretIngredient,coupangSearchKeyword,hook,secretReason,tastePoint};}
async function generateRecipe(accountId,topic,video){const system=`너는 한국 Threads용 레시피 콘텐츠를 만드는 요리 에디터다. 반드시 JSON만 출력한다.
목표: 본문은 3~6줄 생활형 후킹. 첫 댓글은 조리법 없이 저장하기 좋은 재료표와 정확한 계량 중심. 레시피에 실제로 자연스럽게 들어가면서도 사람들이 보고 '어? 이건 하나 사둘 만한데?'라고 느낄 수 있는 차별화 재료 하나를 secretIngredient로 정한다.
문체: 자연스러운 반말, 음슴체 금지, 광고 카피 금지. 가족/지인/전문가에게 들었다거나 직접 써봤다는 경험을 지어내지 않는다. 유명인이 쓴다고 지어내지 않는다.
상품 연결 규칙: 소금/설탕/물/후추/식용유/계란/양파/대파처럼 집에 흔한 기본재료는 secretIngredient로 선택하지 않는다. 일반 고추장/간장/참기름도 다른 자연스러운 선택지가 있으면 피한다. 대신 실제 레시피에 어울리는 참치액, 연두, 육수코인, 냉면육수, 쯔유, 굴소스, 액젓, 맛술, 고추기름, 치킨스톡, 다시팩, 비빔장, 파스타소스, 들기름 같은 '사두면 또 쓰는' 재료를 우선 검토한다. 억지로 넣으면 안 되고 음식과 실제로 어울려야 한다. coupangSearchKeyword는 1~3단어 실제 검색어로 쓴다.
계량은 1스푼, 1/2스푼, 100ml처럼 명확히. 재료 최대 12개. 조리순서는 생성하지 않는다.
JSON={"dishName":"요리명","servings":"1인분","hook":"후킹","tastePoint":"맛 포인트","ingredients":[{"name":"재료","amount":"양"}],"optional":["선택재료"],"secretIngredient":"차별화 재료","secretReason":"왜 어울리는지","coupangSearchKeyword":"검색어"}`;const user=`주제: ${topic}\n참고 YouTube 제목: ${video?.title||'없음'}\n참고 설명: ${video?.description||'없음'}\n실제 레시피를 왜곡하지 않으면서 흔한 기본재료가 아닌 구매 매력 있는 포인트 재료를 골라줘.`;return sanitizeRecipeJson(await callOpenAI(accountId,system,user,1400),topic);}
function buildRecipePostText(recipe){const style=pickOne(POST_STYLES);const hook=recipe.hook||`${recipe.dishName}은 양념 비율 하나만 달라도 맛이 꽤 달라지더라`;const v={problem:`${recipe.dishName} 만들 때\n똑같이 재료 넣는데도 맛이 매번 조금씩 다르잖아.\n\n양념 비율만 정리해두면 훨씬 편해.\n${recipe.servings} 기준은 댓글에 적어둘게.`,difference:`${hook}\n\n재료를 많이 넣는 것보다\n양념 비율에서 맛 차이가 꽤 나더라.\n\n정확한 계량은 댓글에 적어둘게.`,simple:`${recipe.dishName} 복잡하게 볼 필요 없더라.\n\n필요한 재료랑 양념 비율만 딱 정리해두면 편해.\n\n${recipe.servings} 기준은 댓글에 적어둘게.`,ratio:`${recipe.dishName}은 진짜 양념 비율이 중요하더라.\n\n대충 넣으면 매번 맛이 달라져서\n${recipe.servings} 기준으로 정리해봤어.\n\n계량은 댓글에 적어둘게.`,ingredient:`${recipe.dishName} 만들 때\n재료 종류보다 각각 얼마나 넣는지가 더 헷갈리더라.\n\n보기 쉽게 ${recipe.servings} 기준으로 정리해둘게.`,leftover:`${recipe.dishName} 해먹고 싶을 때\n재료 이것저것 찾기 귀찮아서\n필요한 것만 한 번에 보기 좋게 정리해봤어.\n\n댓글에 적어둘게.`};return v[style];}
function buildRecipeCommentText(recipe){const makeIngredients=count=>recipe.ingredients.slice(0,count).map(x=>`▪ ${x.name} ${x.amount}`).join('\n');const optionalLine=recipe.optional.length?`\n✔ 취향껏 ${recipe.optional.slice(0,4).join(', ')} 추가`:'';const lead=pickOne(LINK_LEADS);let text=`✅ ${recipe.dishName} (${recipe.servings} 기준)\n\n${makeIngredients(10)}${optionalLine}\n\n근데 ${recipe.secretIngredient}은 뭐 쓰는지 궁금한 사람 있을 것 같아서\n이 레시피에 어울리는 걸로 하나 골라놨어ㅋㅋ\n${lead}`;if(text.length>270)text=`✅ ${recipe.dishName} (${recipe.servings} 기준)\n\n${makeIngredients(8)}\n\n${recipe.secretIngredient}은 하나 골라놨어.\n${lead}`;if(text.length>240)text=`✅ ${recipe.dishName} (${recipe.servings} 기준)\n${makeIngredients(7)}\n${recipe.secretIngredient}은 아래에만 남겨둘게👇`;return text;}
function scoreCoupangProduct(product,searchKeyword,index=0){const name=String(product?.name||'').toLowerCase();const terms=String(searchKeyword||'').toLowerCase().split(/\s+/).filter(Boolean);const matched=terms.filter(t=>name.includes(t)).length;let score=matched*30;if(terms.length&&matched===terms.length)score+=35;if(product?.rank)score+=Math.max(0,35-Number(product.rank));if(product?.isRocket)score+=8;if(product?.isFreeShipping)score+=4;if(product?.image)score+=2;if(product?.url)score+=2;score+=Math.max(0,12-index);if(/업소용|대용량|말통|식자재|10kg|12kg|14kg|15kg|18kg|20kg/.test(name))score-=45;return score;}
async function chooseCoupangProduct(accountId,searchKeyword){let candidates=[];try{const best=await coupangApi.getBestCategoryProducts(accountId,coupangApi.BEST_CATEGORY_IDS['식품'],30);candidates.push(...best.filter(p=>String(p.name||'').toLowerCase().includes(String(searchKeyword).toLowerCase())).map((p,i)=>({product:p,index:i,source:'best'})));}catch(err){console.log('[Recipe] 쿠팡 식품 베스트 조회 실패 — 검색결과로 폴백:',err.response?.data||err.message);}const searched=await coupangApi.searchProducts(accountId,searchKeyword,10);candidates.push(...searched.map((p,i)=>({product:p,index:i,source:'search'})));if(!candidates.length)throw new Error(`쿠팡에서 "${searchKeyword}" 관련 상품을 찾지 못했습니다`);const unique=[...new Map(candidates.map(x=>[x.product.productId||x.product.url,x])).values()];const ranked=unique.map(x=>({...x,score:scoreCoupangProduct(x.product,searchKeyword,x.index)+(x.source==='best'?25:0)})).sort((a,b)=>b.score-a.score);const winner=ranked[0];console.log(`[Recipe][Coupang] 상품선택 source=${winner.source} score=${winner.score} product="${winner.product.name}"`);return winner.product;}
async function buildRecipeAutopilot({account,target}){const pickedTopic=await pickRecipeTopic(account.id);const topic=pickedTopic.topic;console.log(`[Recipe] 레시피형 시작 — 주제="${topic}"`);const video=await findRecipeVideo(account.id,topic,account.autopilot_youtube_order||'relevance');const recipe=await generateRecipe(account.id,topic,video);if(BORING_SECRET.includes(recipe.secretIngredient)&&HIGH_INTENT.some(x=>recipe.ingredients.some(i=>i.name.includes(x)))){const better=HIGH_INTENT.find(x=>recipe.ingredients.some(i=>i.name.includes(x)));recipe.secretIngredient=better;recipe.coupangSearchKeyword=better;}const product=await chooseCoupangProduct(account.id,recipe.coupangSearchKeyword);const foodPhotos=await findRecipePhotos(recipe,topic);const imageUrl=foodPhotos[0]?.imageUrl||null;const extraImageUrl=foodPhotos[1]?.imageUrl||null;const imageSourceLabel=extraImageUrl?'Pexels 요리사진 2장':imageUrl?'Pexels 요리사진 1장':'없음';console.log(`[Recipe] 핵심 재료="${recipe.secretIngredient}" 쿠팡검색="${recipe.coupangSearchKeyword}" 선택상품="${product.name}"`);return{text:buildRecipePostText(recipe),recipeCommentText:buildRecipeCommentText(recipe),link:product.url,imageUrl,extraImageUrl,imageSourceLabel,product,keyword:recipe.coupangSearchKeyword,trendNote:pickedTopic.trendNote,recipe,youtubeSource:video,pexelsPhotos:foodPhotos,target};}
module.exports={buildRecipeAutopilot};
