const cron = require('node-cron');
const path = require('path');
const fs = require('fs');
const { db, listAllAccountsForSystem, getAccount, canPublish, logUsage, findMediaSourceForProduct, markMediaSourceUsed } = require('./db');
const { publishPost, publishCarouselPost, publishReply, getMediaInsights } = require('./threadsApi');
const coupangApi = require('./coupangApi');
const { generateRecipe: generateContentOnlyRecipe } = require('./contentOnlyAutomation');
const { buildThreadsFirstAutopilot } = require('./autopilotMaterialEngine');
try { db.exec(`ALTER TABLE posts ADD COLUMN recipe_comment_text TEXT`); } catch {}
function hasCoupangKeys(a){return !!(String(a?.coupang_access_key||'').trim()&&String(a?.coupang_secret_key||'').trim());}
function isCoupangLink(link){return /(^|\.)coupang\.com|link\.coupang\.com/i.test(String(link||''));}
function buildDisclosureOnly(account){const t=String(account.coupang_disclosure_template||'이 포스팅은 쿠팡 파트너스 활동의 일환으로, 이에 따른 일정액의 수수료를 제공받습니다.\n\n{link}');return t.replace('{link}','').replace(/\n{3,}/g,'\n\n').trim();}
function trimToLimit(text,limit){const n=String(text||'').trim();if(n.length<=limit)return n;return `${n.slice(0,Math.max(0,limit-1)).trimEnd()}…`;}
function buildDoubleLinkComment(account,prefix,link,maxLength=480){const p=String(prefix||'').trim();const l=String(link||'').trim();const disclosure=isCoupangLink(l)?buildDisclosureOnly(account):'';const links=l?`${l}\n${l}`:'';const tail=[links,disclosure].filter(Boolean).join('\n\n');if(!p)return trimToLimit(tail,maxLength);const available=maxLength-tail.length-2;return `${trimToLimit(p,Math.max(0,available))}\n\n${tail}`.trim();}
const uploadsDir=path.join(__dirname,'uploads');
function localPathFromUploadUrl(url){if(!url)return null;const marker='/uploads/';const idx=url.indexOf(marker);if(idx===-1)return null;return path.join(uploadsDir,url.slice(idx+marker.length));}
function mediaSourceFilesExist(media){const p=localPathFromUploadUrl(media.image_url);if(!p||!fs.existsSync(p))return false;if(media.extra_image_url){const e=localPathFromUploadUrl(media.extra_image_url);if(!e||!fs.existsSync(e))return false;}return true;}
async function buildCommentText(account,post){if(hasCoupangKeys(account)&&post.recipe_comment_text&&!post.link)throw new Error('쿠팡 자동댓글 링크가 비어 있어 댓글 발행을 중단했습니다');if(!post.link)return String(post.recipe_comment_text||'').trim();return buildDoubleLinkComment(account,post.recipe_comment_text||'',post.link,480);}
async function postAffiliateComment(account,post,parentMediaId){if(!post.auto_comment_enabled)return;if(!post.link&&!post.recipe_comment_text)return;try{const commentText=await buildCommentText(account,post);if(!commentText)return;console.log(`[댓글 길이] account #${account.id} post #${post.id}: ${commentText.length}자 link=${post.link?'yes':'no'}`);const commentMediaId=await publishReply(account.id,parentMediaId,commentText);db.prepare(`UPDATE posts SET comment_status='posted', comment_media_id=?, comment_posted_at=? WHERE id=?`).run(commentMediaId,new Date().toISOString(),post.id);console.log(`[댓글 등록 완료] account #${account.id} post #${post.id} -> comment ${commentMediaId}`);}catch(err){const msg=err.response?.data?.error?.message||err.message;db.prepare(`UPDATE posts SET comment_status='failed', comment_error_message=? WHERE id=?`).run(msg,post.id);console.error(`[댓글 등록 실패] account #${account.id} post #${post.id}:`,msg);}}
function startPublishJob(){cron.schedule('* * * * *',async()=>{const now=new Date().toISOString();for(const s of listAllAccountsForSystem()){const account=getAccount(s.id);const due=db.prepare(`SELECT * FROM posts WHERE account_id=? AND status='pending' AND scheduled_at<=? ORDER BY scheduled_at ASC`).all(account.id,now);for(const post of due){if(account.user_id&&!canPublish(account.user_id)){db.prepare(`UPDATE posts SET status='failed', error_message=? WHERE id=?`).run('오늘 발행 가능 횟수를 다 썼습니다 (요금제 하루 한도 초과)',post.id);continue;}try{let mediaId;if(post.image_url&&post.extra_image_url)mediaId=await publishCarouselPost(account.id,{text:post.text,imageUrls:[post.image_url,post.extra_image_url]});else mediaId=await publishPost(account.id,{text:post.text,imageUrl:post.image_url,videoUrl:post.video_url});if(!mediaId)throw new Error('Threads 발행 결과 mediaId가 없습니다');const postedAt=new Date().toISOString();db.prepare(`UPDATE posts SET status='posted', threads_media_id=?, posted_at=?, error_message=NULL WHERE id=?`).run(mediaId,postedAt,post.id);if(account.user_id){logUsage(account.user_id,'publish');console.log(`[발행 횟수 차감] user #${account.user_id} post #${post.id} - Threads 발행 성공 확인 후 1회 차감`);}db.prepare(`INSERT INTO insights (post_id,views,likes,replies,reposts,quotes) VALUES (?,0,0,0,0,0) ON CONFLICT(post_id) DO NOTHING`).run(post.id);await new Promise(r=>setTimeout(r,3000));await postAffiliateComment(account,post,mediaId);}catch(err){const apiErr=err.response?.data?.error;const msg=apiErr?`${apiErr.message} (type: ${apiErr.type||'-'}, code: ${apiErr.code||'-'}${apiErr.error_subcode?', subcode: '+apiErr.error_subcode:''})`:err.message;db.prepare(`UPDATE posts SET status='failed', error_message=? WHERE id=?`).run(msg,post.id);console.error(`[발행 실패][횟수 차감 없음] account #${account.id} post #${post.id}:`,msg);}}}});}
function startInsightsJob(){cron.schedule('*/10 * * * *',async()=>{const start=new Date();start.setHours(0,0,0,0);for(const s of listAllAccountsForSystem()){const posts=db.prepare(`SELECT * FROM posts WHERE account_id=? AND status='posted' AND posted_at>=? AND threads_media_id IS NOT NULL`).all(s.id,start.toISOString());for(const p of posts){try{const stats=await getMediaInsights(s.id,p.threads_media_id);db.prepare(`INSERT INTO insights (post_id,views,likes,replies,reposts,quotes,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(post_id) DO UPDATE SET views=excluded.views,likes=excluded.likes,replies=excluded.replies,reposts=excluded.reposts,quotes=excluded.quotes,updated_at=excluded.updated_at`).run(p.id,stats.views||0,stats.likes||0,stats.replies||0,stats.reposts||0,stats.quotes||0,new Date().toISOString());}catch(e){console.error(`[인사이트 갱신 실패] account #${s.id}:`,e.message);}}}});}
function randomIntervalMinutes(){return 60+Math.random()*15;}const AUTOPILOT_TARGETS=['전체','20대 여자','20대 남자','30대 여자','30대 남자','40대 이상'];
function saveAutopilotPost({accountId,text,link,imageUrl,extraImageUrl,recipeCommentText=null}){db.prepare(`INSERT INTO posts (text,link,image_url,extra_image_url,scheduled_at,auto_comment_enabled,comment_status,account_id,recipe_comment_text) VALUES (?,?,?,?,?,1,'pending',?,?)`).run(text,link||null,imageUrl||null,extraImageUrl||null,new Date().toISOString(),accountId,recipeCommentText);}
function recordAutopilotLast(accountId,keyword,target){db.prepare(`UPDATE accounts SET autopilot_last_keyword=?, autopilot_last_target=? WHERE id=?`).run(keyword,target,accountId);}
async function runContentOnlyAutopilot(account,target){const r=await generateContentOnlyRecipe(account.id,target);saveAutopilotPost({accountId:account.id,text:r.text,link:null,imageUrl:r.imageUrl,extraImageUrl:r.extraImageUrl,recipeCommentText:r.recipeCommentText});recordAutopilotLast(account.id,r.keyword,target);}
function chooseSourceMedia(result){const images=Array.isArray(result?.sourceImages)?result.sourceImages.filter(Boolean):[];if(images.length>=2)return{imageUrl:images[0],extraImageUrl:images[1],imageSourceLabel:'Threads 소재 원본 이미지 2장'};if(images.length===1)return{imageUrl:images[0],extraImageUrl:null,imageSourceLabel:'Threads 소재 원본 이미지 1장'};return{imageUrl:result?.product?.image||null,extraImageUrl:null,imageSourceLabel:result?.product?.image?'Threads 이미지 없음 → 쿠팡 상품 이미지 1장':'이미지 없음'};}
function classifyCoupangUrl(raw){try{const u=new URL(String(raw||'').trim());const host=u.hostname.toLowerCase();const alreadyAffiliate=host==='link.coupang.com'||host.endsWith('.link.coupang.com')||/lptag|subid|aff/i.test(u.search);const plainCoupang=host==='coupang.com'||host==='www.coupang.com'||host.endsWith('.coupang.com');return{valid:/^https?:$/i.test(u.protocol),alreadyAffiliate,plainCoupang,host};}catch{return{valid:false,alreadyAffiliate:false,plainCoupang:false,host:''};}}
async function makeAffiliateLink(account,result){const raw=String(result?.product?.url||'').trim();if(!raw)throw new Error('쿠팡 상품 URL이 비어 있어 자동발행을 중단했습니다');const info=classifyCoupangUrl(raw);if(!info.valid||!info.plainCoupang)throw new Error(`쿠팡 상품 URL 형식이 올바르지 않습니다: ${raw.slice(0,120)}`);if(info.alreadyAffiliate){console.log(`[Coupang][LINK] 이미 파트너스 링크라 딥링크 변환 생략 host=${info.host}`);return raw;}try{const links=await coupangApi.createDeeplink(account.id,[raw]);const first=Array.isArray(links)?links[0]:null;const affiliate=String(first?.shortenUrl||first?.landingUrl||first?.originalUrl||'').trim();if(!affiliate)throw new Error('쿠팡 파트너스 링크 생성 결과가 비어 있습니다');console.log(`[Coupang][LINK] 일반 상품 URL → 딥링크 변환 성공`);return affiliate;}catch(err){const msg=String(err?.message||err?.response?.data?.rMessage||'');if(/url convert failed/i.test(msg)){console.warn(`[Coupang][LINK] 딥링크 재변환 거부 → 검색 API productUrl 그대로 사용`);return raw;}throw err;}}
async function runAutopilotOnce(account){const target=AUTOPILOT_TARGETS[Math.floor(Math.random()*AUTOPILOT_TARGETS.length)];if(!hasCoupangKeys(account)){await runContentOnlyAutopilot(account,target);return;}const cooldown=coupangApi.getApiCooldown?.(account.id);if(cooldown){const e=new Error(`쿠팡 API cooldown 중: ${cooldown.cooldown_until}`);e.code='COUPANG_RATE_LIMIT';e.isCoupangRateLimit=true;throw e;}const result=await buildThreadsFirstAutopilot(account.id,{target});const affiliateLink=await makeAffiliateLink(account,result);const media=chooseSourceMedia(result);saveAutopilotPost({accountId:account.id,text:result.text,link:affiliateLink,imageUrl:media.imageUrl,extraImageUrl:media.extraImageUrl,recipeCommentText:result.commentLead});const last=result.productSearchTerm||result.secretTerm||result.topic;recordAutopilotLast(account.id,last,target);console.log(`[자동발행 예약][V8 COUPANG-LINK-SAFE] account #${account.id} target="${target}" mode="${result.mode}" topic="${result.topic}" product="${result.product.name}" source="${result.sourceUrl}" media="${media.imageSourceLabel}" affiliateLink=yes`);}
function startAutopilotJob(){const nextRunAt=new Map();cron.schedule('* * * * *',async()=>{const now=Date.now();for(const s of listAllAccountsForSystem()){const account=getAccount(s.id);if(!account.autopilot_enabled){nextRunAt.delete(account.id);continue;}if(hasCoupangKeys(account)){const cooldown=coupangApi.getApiCooldown?.(account.id);if(cooldown)continue;}const due=nextRunAt.get(account.id)||0;if(now<due)continue;nextRunAt.set(account.id,now+randomIntervalMinutes()*60*1000);try{await runAutopilotOnce(account);}catch(err){if(coupangApi.isRateLimitError?.(err)){console.error(`[완전자동화 중단][Coupang rate limit] account #${account.id}: ${err.message}`);continue;}console.error(`[완전자동화 실패] account #${account.id}:`,err.response?.data||err.message);}}});}
module.exports={startPublishJob,startInsightsJob,startAutopilotJob};
